# Generated by Django 5.0.6 on 2024-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewspaperEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_date", models.DateField()),
                ("price", models.FloatField()),
                (
                    "articles",
                    models.ManyToManyField(related_name="editions", to="news.article"),
                ),
            ],
        ),
    ]
