# Generated by Django 5.0.6 on 2024-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newspaperedition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
