# Generated by Django 5.0.6 on 2024-06-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newspaperedition_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaperedition",
            name="edition",
            field=models.IntegerField(default=1),
        ),
    ]
