# Generated by Django 4.1 on 2024-07-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_redactor_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaperedition",
            options={"ordering": ["edition"]},
        ),
        migrations.AlterField(
            model_name="newspaperedition",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
