# Generated by Django 4.1 on 2024-07-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_newspaperedition_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["title"]},
        ),
    ]
