from django.urls import path

from news.views import (
    index,
    TopicListView,
    TopicUpdateView,
    TopicCreateView,
    TopicDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDetailView,
    RedactorDeleteView,
    ArticleListView,
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleDeleteView,
    NewspaperEditionDeleteView,
    NewspaperEditionUpdateView,
    NewspaperEditionListView,
    NewspaperEditionCreateView,
    NewspaperEditionDetailView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "articles/",
        ArticleListView.as_view(),
        name="article-list"
    ),
    path(
        "articles/create/",
        ArticleCreateView.as_view(),
        name="article-create"
    ),
    path(
        "articles/<int:pk>/",
        ArticleDetailView.as_view(),
        name="article-detail"
    ),
    path(
        "articles/<int:pk>/update/",
        ArticleUpdateView.as_view(),
        name="article-update"
    ),
    path(
        "articles/<int:pk>/delete/",
        ArticleDeleteView.as_view(),
        name="article-delete"
    ),
    path(
        "newspaper-editions/",
        NewspaperEditionListView.as_view(),
        name="newspaper-edition-list",
    ),
    path(
        "newspaper-editions/create/",
        NewspaperEditionCreateView.as_view(),
        name="newspaper-edition-create",
    ),
    path(
        "newspaper-editions/<int:pk>/",
        NewspaperEditionDetailView.as_view(),
        name="newspaper-edition-detail",
    ),
    path(
        "newspaper-editions/<int:pk>/update/",
        NewspaperEditionUpdateView.as_view(),
        name="newspaper-edition-update",
    ),
    path(
        "newspaper-editions/<int:pk>/delete/",
        NewspaperEditionDeleteView.as_view(),
        name="newspaper-edition-delete",
    ),
]

app_name = "news"
